### ISSUE TITLE
Publish new release to crates.io

### ISSUE THREAD

**Issue by a1phyr** [bnjbvr/file-per-thread-logger#33]
This would avoid having duplicated `env_logger` in dependency tree

**Comment by bnjbvr** [comment]
Yep, good idea!

**Comment by bnjbvr** [comment]
Done in https://github.com/bnjbvr/file-per-thread-logger/commit/8439496fc9e9ba5ad1fe9a58f2ac879af61298ef, thanks for the nudge!
